### ISSUE TITLE
gl-utils dependency

### ISSUE THREAD

**Issue by grey-hat** [gl-inet/bletool#2]
bletool requires gl-util which is not open source, so the community is not able to build this tool from source.

Remove the gl-util dependency.

**Comment by HeFeng1947** [comment]
> bletool requires gl-util which is not open source, so the community is not able to build this tool from source.
> 
> Remove the gl-util dependency.

Thank you for your feedback. We will remove the dependence as soon as possible

**Comment by HeFeng1947** [comment]
> > bletool requires gl-util which is not open source, so the community is not able to build this tool from source.
> > Remove the gl-util dependency.
> 
> Thank you for your feedback. We will remove the dependence as soon as possible

I have removed the gl-util dependency in the new version 3.2.3. Thank you for your feedback again.
