### ISSUE TITLE
ubus error on OpenWRT 19.07

### ISSUE THREAD

**Issue by ghost** [gl-inet/bletool#3]
When trying to run bletool on a build of 19.07 the following is returned:

`root@GL-X750:~# bletool enable
ubus_lookup_id failed.
Invoke Error
`
I have tried this on:
[](https://dl.gl-inet.com/firmware/snapshots/20210131/x750/)
and my own build of 19.07

As OpenWRT 19.07 has a newer version of ubus and libubus which may have some breaking changes that causes it to not work on 19.07.

**Comment by lancersky** [comment]
Hi theBASTI0N,
The version of openwrt-19.07 has not yet been compatible. You need to disable login.sh as follow.
root@GL-X750:/tmp# cat /etc/inittab 
::sysinit:/etc/init.d/rcS S boot
::shutdown:/etc/init.d/rcS K shutdown
#::askconsole:/usr/libexec/login.sh

**Comment by ghost** [comment]
When is it expected that OpenWRT 19.07 will be compatable.

GL-Inet has started creating snapshot with  19.07 and this package is very useful for turning your routers into power IoT gateways.

**Comment by ghost** [comment]
Working on glinet build based on 19.0.7
