### ISSUE TITLE
Memory Leak bletool listen

### ISSUE THREAD

**Issue by ghost** [gl-inet/bletool#4]
Device: x750
Package Version: gl-bletool 3.4.3

When using the command 'bletool listen' the memory used by this consistenly increases until the device memory is full and the command crashes.

![image](https://user-images.githubusercontent.com/29775605/113813310-400caa00-97a2-11eb-9aad-31fd1b9c3a0d.png)

Once the memory usages gets high enough this is received:
![image](https://user-images.githubusercontent.com/29775605/113813784-215ae300-97a3-11eb-8bf8-b80358d26adf.png)

Then about a minute of expected data is received.

The issue may be from the json library and not releasing the memory after the message is sent.

**Comment by HeFeng1947** [comment]
> Device: x750
> Package Version: gl-bletool 3.4.3
> 
> When using the command 'bletool listen' the memory used by this consistenly increases until the device memory is full and the command crashes.
> 
> ![image](https://user-images.githubusercontent.com/29775605/113813310-400caa00-97a2-11eb-9aad-31fd1b9c3a0d.png)
> 
> Once the memory usages gets high enough this is received:
> ![image](https://user-images.githubusercontent.com/29775605/113813784-215ae300-97a3-11eb-8bf8-b80358d26adf.png)
> 
> Then about a minute of expected data is received.
> 
> The issue may be from the json library and not releasing the memory after the message is sent.

Thank you for your feedback. I will test this as soon as possible.

**Comment by HeFeng1947** [comment]
> Device: x750
> Package Version: gl-bletool 3.4.3
> 
> When using the command 'bletool listen' the memory used by this consistenly increases until the device memory is full and the command crashes.
> 
> ![image](https://user-images.githubusercontent.com/29775605/113813310-400caa00-97a2-11eb-9aad-31fd1b9c3a0d.png)
> 
> Once the memory usages gets high enough this is received:
> ![image](https://user-images.githubusercontent.com/29775605/113813784-215ae300-97a3-11eb-8bf8-b80358d26adf.png)
> 
> Then about a minute of expected data is received.
> 
> The issue may be from the json library and not releasing the memory after the message is sent.

I have fixed this issue in version 3.4.5. If there is no new problem, I will close this issue one day later.

**Comment by ghost** [comment]
Hey thanks for the update.
3.4.5 is working as expected.
