### ISSUE TITLE
Error when network up/down

### ISSUE THREAD

**Issue by ghost** [gl-inet/bletool#7]
On occasion when the network goes up and down an error is happening where ble discovery is stopped. Happens if WAN is disconnected/reconnected or if WiFi goes down/up.

When using bletool listen a message "Removed by server" appears.

I am using version 3.4.5 on a x750.

To simulate this:
1. bletool enable
2. bletool discovery
3. bletool listen
4. disconnect and reconnect wan cable. Repeat this until error message is seen.

When using HTOP bledaemon is reloaded when this error occurs.

Cannot build 3.4.6 to test.

**Comment by HeFeng1947** [comment]
> On occasion when the network goes up and down an error is happening where ble discovery is stopped. Happens if WAN is disconnected/reconnected or if WiFi goes down/up.
> 
> When using bletool listen a message "Removed by server" appears.
> 
> I am using version 3.4.5 on a x750.
> 
> To simulate this:
> 
> 1. bletool enable
> 2. bletool discovery
> 3. bletool listen
> 4. disconnect and reconnect wan cable. Repeat this until error message is seen.
> 
> When using HTOP bledaemon is reloaded when this error occurs.
> 
> Cannot build 3.4.6 to test.

Thank you for your feedback. I will test this as soon as possible.

**Comment by ghost** [comment]
If the connection is based on WiFi when down the error will happen multiple times a minutes.

**Comment by HeFeng1947** [comment]
> If the connection is based on WiFi when down the error will happen multiple times a minutes.

This is probably because the output of the kernel is not completely masked.The connection between X750 and Bluetooth module multiplexes the system output serial port. I have informed my colleagues in the routing group to follow up on this issue.

**Comment by HeFeng1947** [comment]
@theBASTI0N Please type "echo 1 4 1 7 > /proc/sys/kernel/printk" in the SSH background and and see if the issue occurs again. Also confirm that you are currently with the latest x750 firmware version(v3.201).

**Comment by ghost** [comment]
Hey thanks for the update.

I am running v3.201.

After running the command I still see the error.

Still looks like network up/down's are causing the bledaemon to restart which causes this issue to remain.

The bletool listen process continues to run even when a restart of bledaemon happens, with Removed by server being the last message printed.

The issue is not the output of _bletool listen_ but **bledaemon restarting**.

**Comment by HeFeng1947** [comment]
> Hey thanks for the update.
> 
> I am running v3.201.
> 
> After running the command I still see the error.
> 
> Still looks like network up/down's are causing the bledaemon to restart which causes this issue to remain.
> 
> The bletool listen process continues to run even when a restart of bledaemon happens, with Removed by server being the last message printed.
> 
> The issue is not the output of _bletool listen_ but **bledaemon restarting**.

This doesn't seem normal.You can turn off bledaemon in the background(type "/etc/init.d/bledaemon stop"), run bledaemon in the foreground(type "bledamon"), and see what log output comes out

**Comment by ghost** [comment]
If you connect your gateway to phone hotspot it is easiest way to test.

I ran the above suggested and in another terminal bletool listen. I get this from bledaemon:
_big endian_

When I turned off my phone AP i get this printed out from bledaemon:

**Segmentation fault**

**Comment by HeFeng1947** [comment]
> If you connect your gateway to phone hotspot it is easiest way to test.
> 
> I ran the above suggested and in another terminal bletool listen. I get this from bledaemon:
> _big endian_
> 
> When I turned off my phone AP i get this printed out from bledaemon:
> 
> **Segmentation fault**

I have pushed the new code, please test whether the issue has been successfully fixed.

**Comment by ghost** [comment]
Thanks for the update. THis seem to have fixed the issue. I have not been able to get it to happen again.
