### ISSUE TITLE
Error when trying to write to characteristic

### ISSUE THREAD

**Issue by Emb3ddev** [gl-inet/bletool#9]
Hello, there seems to be ubus implementation error. When attempting to send data to bluetooth device, subscription for ubus fails, causing bletool-api to get stuck & broken.

Device used: Convexa-S1300
OS: OpenWrt 18.06-SNAPSHOT
bletool branch: master, commit 7ef5ea52b0335f78ee7406cf30db7c53fedd8364

Test procedure (there is 2 second delay between all commands.):
1. Connect to ble device
2. Get list of all services
3. Find correct service
4. Get all characteristics using found service handle
5. Find correct characteristic handle
6. Write 0x01 to characteristic | <- error occurs here
7. Disconnect from ble device 
 
Here is the stdout:
> gl_ble_write_char(mac, char_handle, tmp_data, response_flag);
> Removed by server
-> returns 0, took 2s 
> 
> gl_ble_disconnect(mac);
> Ubus lookup id failed.
> err|gl_bleapi.c|gl_ble_disconnect(513): Response missing!
-> returns 2, took 0s

There is no recovery after "Removed by server". Subscriber thread is stuck and only way to recover Bluetooth is to terminate program & start it again.

**Comment by HeFeng1947** [comment]
This appears to be a problem with the ubus service. I recommend switching to without-ubus(https://github.com/gl-inet/bletool/tree/without-ubus) branch testing.
